[package]
name = "amm_snip20"
version = "0.1.0"
authors = ["Asparuh Kamenov <asparuh@hack.bg>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
amm_shared = { path = "../../libraries/amm_shared" }
